### ISSUE TITLE
Not enough observations

### ISSUE THREAD

**Issue by weswitt** [jonathankoren/weewx-aqi#27]
I am trying to get weewx-aqi working with my custom weather station.  My weather station has an air quality sensor that emits sensor readings every 2 seconds.  These readings are used to generate loop packets in my driver.  The air quality readings are not stored anywhere.  I've configured weeewx-aqi to use the weewx archive records as the sensor database (data_binding = wx_binding).  The weewx-aqi extension runs just fine but I get "Not enough observations" errors and nothing is written to the aqi database.  My guess is that this is caused by the fact that the sensor store in my case is just the weewx archive records and there is clearly not enough data to satisfy the weewx-aqi extension.  My idea to fix this is to create a real AQI sensor store that my weather station driver would write into.  I would then configure weewx-aqi to to this.  This seems like it would make this work.  Does this sound like a correct analysis?

Aug 22 15:14:14 weewx-test /weewxd: AqiService: ValueError AQI calculation for pm2_5 on 1629645240 failed: Not enough observations wanted 540, but got 16
Aug 22 15:14:14 weewx-test /weewxd: AqiService: ValueError AQI calculation for pm10_0 on 1629645240 failed: Not enough observations wanted 540, but got 16
Aug 22 15:14:14 weewx-test /weewxd: AqiService: not storing record for dateTime 1629645240

**Comment by jonathankoren** [comment]
The most common reason someone sees "not enough observations", is because there are not enough observations to correctly calculate the AQI for the pollutant for the configured standard. For instance, a PM 2.5 US EPA NowCast requires **12 hours** of continuous observations, with each hour having at least 75% of expected observations. 

In the log you you pasted, it looks like 16 data points were found in the DB, but you need 540 in order to calculate an AQI.

If this has been running for more than 12 hours, then this would be indicative of a problem. However, if you do not have 12 hours observations in your DB, then something may be wrong. 

My first two questions are:

1. How long have you *should* you have been recording data? 

2. Are the observations actually being written to the DB? It looks like 16 were, so maybe that's not the issue? I don't know. It depends on what the answer to question 1 is.
 
My advice is simply to wait, but since it's been 13 hours since you posted this, I guess you can check after your read this. :)

**Comment by weswitt** [comment]
thanks for the response.

i changed the data source that i'm providing to weewx-aqi.  my data source emulates what purple-air provides -- a sql database with sensor reading values.  once i did this everything works perfectly.  weewx-aqi thinks it's talking to a purple-air database and all is good.

my next task it to add mqtt support to weewx-aqi so that the aqi values are reported out over mqtt and can be used by devices outside of weewx.

**Comment by jonathankoren** [comment]
Awesome. Great to hear this.
