### ISSUE TITLE
UK DAQI aqi.sdb

### ISSUE THREAD

**Issue by steepleian** [jonathankoren/weewx-aqi#7]
A question. I am using the UK DAQI. I notice that the category columns are all populated in the aqi.sdb database with zero. Is this correct? I am still getting a background colour but as the readings are at index 1 at the moment have yet to see if this will change when index increases. Am I correct in thinking the category is linked to colour or is it different for DAQI.

I am using a SDS011 particle sensor which measures PM2.5 and PM10 only with the weewx-sds011 driver. 
![Screenshot from 2020-05-12 09 44 51](https://user-images.githubusercontent.com/18438654/81662368-5fd20b80-9435-11ea-8c7b-c53bf5aa7b20.png)

Thanks
Ian

**Comment by jonathankoren** [comment]
My initial thoughts is that this is a configuration error. The UK and US AQI calculations use the same code, so I doubt that it's something code related.

It's impossible for me to tell what the proper value should be, since this doesn't contain the readings from the sds011. I will say that that UK DAQI is defines PM 2.5 and PM 10.0 in microgram_per_meter_cubed , which does seem to be the output of weewx-sds011 https://github.com/matthewwall/weewx-sds011/blob/master/bin/user/sds011.py#L211 . However, it doesn't look like it's setting the units on the column.

I've filed an issue against weewx-sds011, but I'll add a fix on my side that will assume that units are as expected if they are not set.

Are you using the py2 release, or the py3 release?

**Comment by steepleian** [comment]
I can confirm that the SDS011 uses microgram_per_meter_cubed.
Regarding Python version, I am using 3
Thank you

**Comment by jonathankoren** [comment]
I submitted a patch to weewx-sds011 to set units on the measurements. https://github.com/matthewwall/weewx-sds011/pull/3

Additionally, I added two fixes on the weewx-aqi side via https://github.com/jonathankoren/weewx-aqi/pull/10 . First, weewx-aqi now assumes that the measurement units are in whatever units they need to be for the configured AQI standard. However, it spams the logs with a warning if the units are missing. I'd recommend patching your local sds011.py with my changes. (They're a trivial paste at the top of the file. See the PR linked above.) Second, weewx-aqi wasn't correctly merging temperature and pressure information from the main weather db when the air quality sensor doesn't have it. That now happens. 

I've merged these changes into master, and have created a new release v1.3 .

**Comment by jonathankoren** [comment]
As far as the composite is null and the PM 2.5  & 10.0 being all at index 1 and category 0, that's hard to determine. the DAQI is only has integers on [1, 10] and currently all of the Britain is forecasted to be at DAQI 1 for the next few days. When recalculating DAQI using my data, I saw a range of values over the course of a couple of years, which makes sense due to the smoke from the Northern California forest fires a couple of years ago. I believe it's calculating the DAQI correctly.
